# Generated by Django 5.2 on 2025-05-16 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_item_category_item_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock_out',
            name='emp_name',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.CreateModel(
            name='stock_in',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('reciever', models.CharField(max_length=250)),
                ('remarks', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.category')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.item')),
            ],
        ),
        migrations.DeleteModel(
            name='stock',
        ),
    ]
