# Generated by Django 5.2 on 2025-05-16 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_stock_out_emp_name_stock_in_delete_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock_in',
            old_name='item',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='stock_out',
            old_name='item',
            new_name='name',
        ),
    ]
