# Generated by Django 5.2 on 2025-05-16 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_item_stock_in_name_rename_item_stock_out_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock_in',
            old_name='name',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='stock_out',
            old_name='name',
            new_name='item',
        ),
    ]
