# Generated by Django 5.2 on 2025-05-18 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_name_stock_in_item_rename_name_stock_out_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock_in',
            old_name='date',
            new_name='date_of_entry',
        ),
        migrations.RenameField(
            model_name='stock_out',
            old_name='date',
            new_name='date_of_issue',
        ),
    ]
