# Generated by Django 5.2 on 2025-05-18 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_date_stock_in_date_of_entry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock_in',
            name='date_of_entry',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='stock_out',
            name='date_of_issue',
            field=models.DateField(),
        ),
    ]
