# Generated by Django 5.2 on 2025-05-18 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_stock_in_date_of_entry_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='stock_in',
            new_name='StockIn',
        ),
        migrations.RenameModel(
            old_name='stock_out',
            new_name='StockOut',
        ),
    ]
